version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
