version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
